# Generated by Django 3.2.16 on 2023-05-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(max_length=17, primary_key=True, serialize=False, unique=True, verbose_name='id'),
        ),
    ]
